/**
 * The built-in theme templates (theming addendum 2026-10-02 §3, "Mitgelieferte
 * Vorlagen"): Fokus, Klar & Warm, System / Raster, Werkbank and the demo theme
 * Rotecodefraktion. Editorial is the reference design and therefore the
 * default theme, not a template.
 *
 * The data is generated by `scripts/themes-from-mockups.ts` into
 * `builtin-themes.data.ts` (and, identically, `themes/<slug>.yaml`). The
 * library lists these with origin `builtin`; they cannot be deleted or
 * overwritten.
 */
import { builtinThemeData } from './builtin-themes.data.js'
import type { ThemeFile } from './theme-file.js'

export interface BuiltinTemplate {
  slug: string
  name: string
  file: ThemeFile
}

/** A fresh copy per call, so a caller that edits a template cannot change the shipped one. */
export function builtinTemplates(): BuiltinTemplate[] {
  return builtinThemeData.map(({ slug, file }) => ({
    slug,
    name: file.name ?? slug,
    file: {
      ...file,
      ...(file.base && { base: { ...file.base } }),
      ...(file.light && { light: { ...file.light } }),
      ...(file.dark && { dark: { ...file.dark } }),
    },
  }))
}
